### ISSUE TITLE
Only show stdout in email

### ISSUE THREAD

**Issue by ibizaman** [nfultz/nb2mail#3]
Would it be possible to add an option so that this tool only captures stdout (or a given fd) and only puts that in the email?

This way we could have debug output going to stderr that wouldn't show up in the email.

**Comment by nfultz** [comment]
Removing the error messages from the email is as simple as editing the template (`mail.tpl`)  and commenting out the error section -  getting fancier and printing the errors to the console would probably require somehow reattaching the jupyter kernel's stderr to the console instead of the jupiter cell output -- possible, but not from a TemplateExporter or a PostProcessor.
